security:
    encoders:
            AppBundle\Entity\User: bcrypt
    providers:
        my_db_provider:
                      entity:
                            class: AppBundle\Entity\User
                            property: apiKey
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            guard:
                authenticator: AppBundle\Security\TokenAuthenticator
